### PR TITLE
Simplyfied Api

### PR DESCRIPTION
**Pull request by mclausen**
- Made extension method to encapsulate registration, this makes it easier to register polymorphic types as well as limiting the api surface area
- In addition i made the PolymorphismDocumentFilter, PolymorphismSchemaFilter and TypesPasser internal, for reasons described in previous bullet

### CODE REVIEW

**Comment by KennethJakobsen** [comment]
Great work even though i'm sad to see the type spasser go!

**Comment by mclausen** [comment]
Haha! I was thinking about killing it, but decided i needed get killed in its own pr 😎
		
		

		
	





On Mon, Mar 12, 2018 at 5:31 PM +0700, "Kenneth Jakobsen" <notifications@github.com> wrote:












Merged #1.

**Comment by KennethJakobsen** [comment]
Also it has a purpose, arrays and params don't mix well

**Comment by mclausen** [comment]
I agree to some extend. Maybe it you can do a params Type parameter, or make it an enumerable collection that you’ll pass, then it would play nicely with a linq statement etc.?
		
		

		
	




On Mon, Mar 12, 2018 at 6:04 PM +0700, "Kenneth Jakobsen" <notifications@github.com> wrote:












Also it has a purpose, arrays and params don't mix well

**Pull request merged**
